services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
    image: hyperparameter-tuning:latest
    env_file: ".env"
    command: --wandb-project hyperparameter-tuning
    # Save model checkpoints to your local machine
    volumes:
      - ./models:/app/models
